### ISSUE TITLE
Add links to report issues

### ISSUE THREAD

**Issue by Matic0B** [MCResourcePile/MCResourcePile.github.io#10]
Add links somewhere on the pages to link to here so people can report issues or suggest features for parts of the website.

**Comment by CrazyCreeper521** [comment]
Maybe something like...
`<footer>
                            <ul class="nav nav-pills">
                                <li class="resourcepile-copyright-year"></li>
                             
                              <li class="pull-right"><a href="../../revisions/website">Revisions</a></li><li class="pull-right"><a href="https://github.com/MCResourcePile/MCResourcePile.github.io/issues">Report an Issue</a></li>
                                
                            </ul>
                        </footer>`
It'll display a little link at the footer along with the Revisions link.
![image](https://cloud.githubusercontent.com/assets/7937351/22159219/e6d6e672-df0d-11e6-8d93-2fa4aebace6e.png)

**Comment by JexeI** [comment]
I've done this for the homepage, will make a PR updating it globally soon.

**Comment by JexeI** [comment]
#39
