### ISSUE TITLE
Replace Lifeboat with Overcast

### ISSUE THREAD

**Issue by mitchiiii** [MCResourcePile/MCResourcePile.github.io#12]
Once Lifeboat drops PGM support, replace any links to Lifeboat with Overcast Network and PGM. Map images will have to be moved to our repos as maps.oc.tc probably won't stay up much longer.

**Comment by applenick** [comment]
👍

**Comment by mitchiiii** [comment]
https://github.com/MCResourcePile/MCResourcePile.github.io/pull/36
