### ISSUE TITLE
pgm.json - Fairy Tales 3 incorrect map name/slug

### ISSUE THREAD

**Issue by Palmidence** [MCResourcePile/mcresourcepile.github.io#163]
`Fairy Tales 3: Metamorphose` is named `Fairy Tales 2: Metamorphose` - Fairy Tales 2 is A Tale or Two

**Comment by CrazyisCreeps** [comment]
Wait it's supposed to be 3? I thought the map name was just "Fairy Tales: Metamorphose"

**Comment by CrazyisCreeps** [comment]
oh no I see
