### ISSUE TITLE
Use Crafatar for all user avatars

### ISSUE THREAD

**Issue by Matic0B** [MCResourcePile/MCResourcePile.github.io#26]
Staff pages use minotar while uses crafatar. Use one across the whole website not both.

**Comment by mitchiiii** [comment]
Crafatar accepts UUID while Minotaur doesn't. Minotaur supports skin layers while Crafatar doesn't.

**Comment by mitchiiii** [comment]
Appears Crafatar does actually support skin layers though a setting.
