### ISSUE TITLE
Replace links on MapStack CONTRIBUTING.md

### ISSUE THREAD

**Issue by CrazyCreeper521** [MCResourcePile/MCResourcePile.github.io#27]
> Contributions to MapStack
>
>All maps listed on MapStack are stored within a javascript file called map-listing.js which is located under each of the network's individual folder, under the materials folder, which is under the assets folder. The lifeboat.html or avicus.html in the mapstack folder does not need to be edited.
>
>Lifeboat PC bow records: assets/materials/lifeboat/map-listing.js
>Avicus Network bow records: assets/materials/avicus/bow-records.js

The links to the bow records need to be removed, and replaced with the correct links

**Comment by triplezko** [comment]
fixed
