### ISSUE TITLE
Add total kills/deaths stat

### ISSUE THREAD

**Issue by Matic0B** [MCResourcePile/MCResourcePile.github.io#33]
Right before Lifeboat PC shuts down oc.tc copy kills and deaths stats to add to objective leaderboards

**Comment by RubeVi** [comment]
Try to save the nomined profiles, because (i think) the website will be shutdown the 31

**Comment by freundTech** [comment]
I think we can forget that one... :/

**Comment by Matic0B** [comment]
Cache?
