### ISSUE TITLE
GitHub ratelimiting downloads to ~10 per hour

### ISSUE THREAD

**Issue by qlados** [MCResourcePile/mcresourcepile.github.io#43]
I've downloaded a couple maps and now dls dont start :c

**Comment by freundTech** [comment]
Which maps don't work?
Downloading works fine for me, although I didn't test all maps.

**Comment by qlados** [comment]
After I downloaded some maps it just doesn't start :C

**Comment by freundTech** [comment]
I think I found the problem. GitHub is rate limiting the download to 60 requests per user per hour. I'll talk to the other people about what we can do about that.

In the meantime just try again in an hour or download the maps directly from GitHub:

* https://github.com/MCResourcePile/overcast-cardinal-maps
* https://github.com/MCResourcePile/overcast-maps
* https://github.com/MCResourcePile/overcast-unofficial-maps
* https://github.com/MCResourcePile/avicus-maps

Error message for the other devs:
```json
uncaught exception: {"readyState":4,"responseText":"{\n  \"message\": \"API rate limit exceeded for 87.173.74.54. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\n  \"documentation_url\": \"https://developer.github.com/v3/#rate-limiting\"\n}\n","responseJSON":{"message":"API rate limit exceeded for 87.173.74.54. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"},"status":403,"statusText":"Forbidden"} ERROR
```

**Comment by qlados** [comment]
How do I download directly from there?

**Comment by freundTech** [comment]
Click the link, then on that page click the green "Clone or Download" button and click "Download Zip". This will download a zip with all the maps from that repository. Downloading individual maps sadly isn't possible like that.

**Comment by qlados** [comment]
I dont see the button

**Comment by qlados** [comment]
nvm
