### ISSUE TITLE
Map thumbnail updates

### ISSUE THREAD

**Issue by mitchiiii** [MCResourcePile/MCResourcePile.github.io#47]
- Convert to global template which all MapStack pages use
- Separate official and unofficial maps
- Link to thread instead of displaying CC for sourced maps 
- Make it more clear which license maps are using without having to look in the download modal (maybe a badge?)
- Might be some other little things

**Comment by RubeVi** [comment]
https://github.com/OvercastNetwork/maps.oc.tc

**Comment by mitchiiii** [comment]
We still need to keep a copy of XMLs for compression and other modifications we make @RubeVi
