### ISSUE TITLE
Validate forms before submission

### ISSUE THREAD

**Issue by mitchiiii** [MCResourcePile/mcresourcepile.github.io#53]
https://mcresourcepile.github.io/forms/maps

**Comment by triplezko** [comment]
- [ ] Fix contact form 
  - White margin on bottom of page
  - Red line under submit button and discord/email textbox for error
- [ ] Fix apply form marking yes for all three positions regardless of what is chosen.
- [ ] Make any discord field follow abcd#1234 format.
