### ISSUE TITLE
Missing maps

### ISSUE THREAD

**Issue by CrazyisCreeps** [MCResourcePile/mcresourcepile.github.io#69]
We've gotten permission for all these maps, they just need to be loaded.

**Avicus Maps**

- [ ] Homo 'non est Calidus by XUPH with a non-commercial license

- [ ] Frozen Horizon with a commercial license

- [ ] Snowy Overworld by Passively with a commercial license

**OCN Maps**

- [x] Hallowed Harb (Plastix made Harb)

- [x] Fortress Battles: Easter with a commercial license
- [x] SuperPRISM with a commercial license

**Comment by mitchiiii** [comment]
Added to map repos, will be on the site later today or tomorrow.

**Comment by CrazyCreeper521** [comment]
I'll just reopen this instead of making a new issue, a few guys got back to me allowing us to use even more maps.

- [ ] Ro_G's maps with a commercial license

- [ ] Strmr's maps with a commercial license

**Comment by CrazyCreeper521** [comment]
Added more maps to the OP
