### ISSUE TITLE
"TO DO" for Contest pages 

### ISSUE THREAD

**Issue by Matic0B** [MCResourcePile/mcresourcepile.github.io#72]
Things are not organized based on priority or anything.

**Issues / Fixes:**

- [x] Remove /contest/overcast from navbar as there is no content
- [x] Make table fit in the container, it goes out on the sides
- [x] Clicking on a persons name in map thumbnails doesn't do anything (should probably search for them in the maps page)
- [x] Fix submission details on Mini map making competition page (the dates listed are for the current destroy competition)

**Improvements:**

- [x] Add markers to table to show that it can be organized
- [x] Organize map thumbnails in an alphabetical order
- [x] Change icon for contests in navbar to something else so it's not the same as maps (there's an icon for just one block)
- [x] Make top row in the table bold (categories)

**New features:**

- [x] Add numbers in badges (1, 2 etc but # in front) to map thumbnails to show map ranking (best to worst score)
- [x] Add numbers (1, 2 etc but # in front) in a new column in the table in front of map names showing their ranking
- [x] Make gamemode text clickable so once you click it, it links to the maps page searching for that gamemode (*Read comments below - 2*)
- [x] Add map authors underneath map name for top three maps in the podium (make the text quite small so it doesn't change the look too much)

**Other:**

- [x] Add page for ongoing Stratus map contest
- [x] Add pages for Overcast map contests (what we have)
- [ ] Once things are done and content is added, write an update post
- [x] *Possibly* rename "Competitive" in the navbar to something that might suit map contests better

**Comments**

**(1)** Have the images behave the same way the name does, once clicked
**(2)** The links (on image, name and authors) that lead to map pages should lead to the new stratus page that will go up as there are a lot of maps we can source from stratus. The issue is, how will we choose if it links to Stratus or PGM map page as some of them might be loaded in the repo and others not. That would split the maps into two categories and the link would need to know which one to go to. **Or add a contest tag to map thumbnails that we can use and have all on stratus pages since they were made for stratus.**
**(3)** If a custom panel has more than 3 or 5 lines of content, add a button that once clicked expands the panel fully but hides everything except top 3 or 5 lines of content (example: Destroy map making competition).

**Comment by mitchiiii** [comment]
> (3) If a custom panel has more than 3 or 5 lines of content, add a button that once clicked expands the panel fully but hides everything except top 3 or 5 lines of content (example: Destroy map making competition).

Be selective with what you put into them. Half that information isn't completely relevant to the purpose of these pages.

**Comment by mitchiiii** [comment]
> (2) The links (on image, name and authors) that lead to map pages should lead to the new stratus page that will go up as there are a lot of maps we can source from stratus. The issue is, how will we choose if it links to Stratus or PGM map page as some of them might be loaded in the repo and others not. That would split the maps into two categories and the link would need to know which one to go to. Or add a contest tag to map thumbnails that we can use and have all on stratus pages since they were made for stratus.

The best we can do is have a link to a page searching for the map, and if it's there it's there.. if not, then bad luck. The `"map-group": "...",` for the contest pages **should** match one of the map pages, so that isn't an issue.

**Comment by mitchiiii** [comment]
> (1) Have the images behave the same way the name does, once clicked

Why?

**Comment by Matic0B** [comment]
@mitchiiii 
About the 2: Guess we just use the Stratus one then, not sure what we can do with the maps that didn't make it and were submitted though. Put them on Stratus and custom mark them?

About the 1: Easier to click and theres nothing really there at the moment that would use clicking the image. Might as well just have it link to the map page in the stratus maps

**Comment by mitchiiii** [comment]
Cannot sort scores table by total score.
