### ISSUE TITLE
Contacted map authors list - OCN

### ISSUE THREAD

**Issue by CrazyisCreeps** [MCResourcePile/mcresourcepile.github.io#74]
Please don't edit this list for any reason unless you're adding another author who has been contacted.

# Map authors who have given us permission
> These map authors have given us permission to use their maps, and the maps are either on the site or on the list of maps to add.

- AllttA

- amactus

- AMo

- AntandRocky

- Anthonny

- Arzanex

- AtlasGames

- Avaleer

- BeanButt

- Beebou

- bend

- bleangamer

- Brottweiler

- CacklingPanda

- Carterpaul

- ch4teau

- chle_

- Claf

- CoWinkKeyDinkInc

- Creephunter

- D347HxD

- daeshik

- Daffy_Duck01

- dewtriod

- DiamondAx

- Diamyx

- DoctorTardi

- Doomyboy

- Draeyx

- Elijah

- felipu_feliu

- Flashee

- GabeIsAwsome199

- GammaRay89

- GoldenOre

- gushingblood

- halfmaster1

- HardstyleRaver2

- HoldfastGames

- iLifting

- ItzaMeLuigi

- JonnyBallgame

- JSBach

- Jtr

- Kaleeka

- KasiCrafter

- Kaskito

- koipen

- Kroest

- Lyzak

- Matic0B

- Mattato

- matt772 

- McFanta_

- Mikeg542

- mitchiii_

- Moo8x8

- MrArchy

- NadaStorm

- Nanu

- nintendoboy11

- nixter1029

- Obelistics

- OllieGamerz

- ollyj

- Omnigarde

- Oversoul96

- Oxinous

- pbat

- PepsiDog

- pikpikmerchant

- PlasmaCross

- Plastix

- Qixit

- raid3r

- Rasta_Jol

- Reshif

- Rixiot

- Ro_G

- SailorMojo

- samthecat43

- SheriffSoco

- Skirmisher47

- snatimal

- StealthMedia

- Strmr

- Teh_Myth

- TheNoChillDude

- Thungon

- Timotheeee

- Torn_Ares

- UnPhair 

- ViceWaterColour

- Vytr

- whiskers434

- whiteveR

- Without_Regret

- xCand

- Yoyo_

- Zan

- _3Each

# Map authors who have not given us permission
> These map authors have not allowed us to use their maps, or have not allowed us to use any maps that have not been co-created by anyone else that we have permission to use.

- Chicky

- Cubist

- Eclipsen

- ElectroidFilms

- Equus

- Pugzy

- rockymine

- Strangey

- Tjandra

- Tywnis

- _DISTRACTION

# Map authors who we're still waiting to hear back from
> These map authors have been contacted, but we have not heard a response from. It could be worth contacting these people again, maybe on a different platform.

- BlockDrop74

- Brumlington

- crikimaruc

- JETUB1

- McSpider

- McYukon

- Mono0

- oib5

- SajinZero

- Syvoxo

# Map authors who do not need to be contacted further
> These maps authors were contacted at one point in the past, but co-authors to all their maps have already given permission for us to use them.

- auxdempster

- BrunoTheMiner

- Dino_Saurus

- FlavorfulGecko5

- TiggyLi

- TruBuild

- SpooksMcKenzie

# Map authors who have not been contacted
> These maps authors have not been contacted yet. Feel free to add anyone to this list.

- __gavin

- Eclipsen

- LEGITME

- OurLoneHero

- Pyrolith

- SajinZero

- Solo_Runner

- thegoodguy

- way2hot4rs

**Comment by mitchiiii** [comment]
https://github.com/MCResourcePile/mcresourcepile.github.io/projects/1
