### ISSUE TITLE
Contacted map authors list - Avicus (Throwback/MCZone maps)

### ISSUE THREAD

**Issue by Palmidence** [MCResourcePile/mcresourcepile.github.io#75]
Please don't edit this list for any reason unless you're adding another author who has been contacted.

**NOTE:** This isn't a general Avicus one, but rather maps that were formerly used for the Throwback server due to the possible difficulties in contacting older map creators.

# Map authors who have given us permission
> These map authors have given us permission to use their maps, and the maps are either on the site or on the list of maps to add.

- [x] Matic0B (Clay Wars)
- [x] KooDaLord (Scorpio)
- [x] Pavlo
- [x] Evocal (Formorgar I, Justice I, Block Fort)
- [x] funkystudios (Halcyon I, Actrix)

# Map authors who have not given us permission
> These map authors have not allowed us to use their maps, or have not allowed us to use any maps that have not been co-created by anyone else that we have permission to use.

- [x] ParaPenguin / Haribo98 (Ternio, Senex I, Senex II, Rendezvous I, Rendezvous II, Gladiator) 

_None currently_

# Map authors who we're still waiting to hear back from
> These map authors have been contacted, but we have not heard a response from. It could be worth contacting these people again, maybe on a different platform.

- [ ] G_SKIPPY (Fissura, Quintus, Luar, Divines)
- [ ] Naskel (Zalidor, Vallis)

# Map authors who have not been contacted
> These maps authors have not been contacted yet. Feel free to add anyone to this list.

- [ ] Bumblebeetle13 (Dust Devils)
- [ ] Jessamania (Castle Adventure)
- [ ] Awarrior/Fouled/Lavish (Sandstorm)

**Comment by CrazyCreeper521** [comment]
#90

This will be closed in favor of that other list, which covers all parts of Avicus. This info has been transferred to the new issue
