### ISSUE TITLE
Contacted map authors list - Avicus

### ISSUE THREAD

**Issue by CrazyisCreeps** [MCResourcePile/mcresourcepile.github.io#90]
Please don't edit this list for any reason unless you're adding another author who has been contacted.

**NOTE**: There already is a list for contacted map author info (#75), however since that list is just for Throwback maps, this one will replace it and all info from that issue will be transferred to this one.

# Map authors who have given us permission
> These map authors have given us permission to use their maps, and the maps are either on the site or on the list of maps to add.

- cellish

- CrazyClownz

- Crimson_Aught

- dcstarwars

- Evocal

- funkystudios

- izjust4fun

- joelous

- Kojak

- KOODALORD

- K_R_Cord

- Legoche 

- Myv

- ParaPenguin (aka. Haribo98)

- PieZ

- Prodigy4532

- profbananaslug 

- ProfessorUtonium

- resepignev

- Riilo

- Spookeh

- steven5703

- Stuarts

- ViceWatercolour (aka. Squiddard)

- XUPH

# Map authors who have not given us permission
> These map authors have not allowed us to use their maps, or have not allowed us to use any maps that have not been co-created by anyone else that we have permission to use.

- Clijmart

- GrapeSmoothie

- Matic0B

# Map authors who we're still waiting to hear back from
> These map authors have been contacted, but we have not heard a response from. It could be worth contacting these people again, maybe on a different platform.

- Fouled

- G_SKIPPY

- Naskel 

- Numberz_

- Pavlo

- Bumblebeetle13 

- PrinceRelyt / XVenom17 

# Map authors who do not need to be contacted further
> These maps authors were contacted at one point in the past, but co-authors to all their maps have already given permission for us to use them.

# Map authors who have not been contacted
> These maps authors have not been contacted yet. Feel free to add anyone to this list.

- Awarrior (Exzyy : ByExzyy [Skype])

- Jessamania 

- Lavish (calwhovian)

- MerlinMaster 

- Polar_Express

**Comment by mitchiiii** [comment]
https://github.com/MCResourcePile/mcresourcepile.github.io/projects/3
