### ISSUE TITLE
An Error Occurred While Preparing Download  

### ISSUE THREAD

**Issue by Minertedtoad** [MCResourcePile/mcresourcepile.github.io#98]
I can't  #download any maps and it comes up with a error all the time! I have tried reseting the access token and that doesn't work!

![image](https://user-images.githubusercontent.com/34043323/35296198-330e79e2-0073-11e8-8177-e8e6951d8d73.png)

I want to open a server with a lot of these maps but With me only being able to download 7 an hour and now this happening it seems along way away

**Comment by pcteddy** [comment]
I am having the same issues

**Comment by Matic0B** [comment]
We've changed something recently.
@mitchiiii

**Comment by mitchiiii** [comment]
Does this only happen after you download 6-8 maps?

**Comment by mitchiiii** [comment]
@Minertedtoad @pcteddy When you go to your [preferences](https://mcresourcepile.github.io/admin/preferences) does your GitHub name appear in the access token panel? Is there anything in the console showing errors?

**Comment by Minertedtoad** [comment]
![image](https://user-images.githubusercontent.com/34043323/35344614-7866da5e-0125-11e8-9cda-bc4a9d45bafe.png)
This is what appears @mitchiiii

**Comment by Minertedtoad** [comment]
![image](https://user-images.githubusercontent.com/34043323/35358383-6385e08e-014e-11e8-9d69-8c848b103499.png)

**Comment by mitchiiii** [comment]
Try removing &scope= and everything after that from the token and save it. See if the error persists.

**Comment by mitchiiii** [comment]
Should be fixed as of https://github.com/MCResourcePile/mcresourcepile.github.io/commit/93607f8da8d00bf6144f6ec4a05c712a201956bd.
